# Generated by Django 4.1.1 on 2022-11-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangareader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Array and Hashing', max_length=200),
            preserve_default=False,
        ),
    ]
