# Generated by Django 4.1.1 on 2022-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangareader', '0002_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='questions',
            field=models.ManyToManyField(to='mangareader.question'),
        ),
    ]
