# Generated by Django 4.1.1 on 2022-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangareader', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
