# Generated by Django 4.1.1 on 2022-11-29 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangareader', '0006_question_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 29, 6, 5, 20, 276759, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
